name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest discover tests/unit
        python -m unittest discover tests/integration
    - name: Run linter
      run: |
        pip install flake8
        flake8 src/
    - name: Check README
      run: |
        if [ ! -f README.md ]; then
          echo "README.md file is missing"
          exit 1
        fi
        if ! grep -q "NVIDIA RAG Q&A Chat Application" README.md; then
          echo "README.md does not contain expected content"
          exit 1
        fi
